version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /lee/apps/docker-react-app/node_modules
      - ./:/lee/apps/docker-react-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /lee/apps/docker-react-app/node_modules
      - ./:/lee/apps/docker-react-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]